spring:
  profiles: production
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1247 FROM DUAL
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
  logging: ##LOGGING
    level:
      root: none
      sql: none
    charset:
      console: UTF-8
      file: UTF-8
    file:
      name: ./logs/out.log

CONSTANTS:
  ISDEVMODE: "false"

