server: ## PORT
  port: 8080

spring:
  profiles: ##PROFILES
    active: local,production
  jpa:  ## HIBERNATE
    hibernate:
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    repositories:
      enabled: true
    open-in-view: false
  output: ##CMDLN
    ansi:
      enabled: always

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect


CONSTANTS:
  PROJECTNAME: "SPRING_BASE"
  SALTVALUE: "salt"


